version: "3"
services:
  piglatin:
    build: ./piglatin
    environment:
      PORT: ${PORT}
      DEBUG: ${DEBUG}
      DATABASE_ENGINE: ${DATABASE_ENGINE}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: ${DATABASE_PORT}

    ports:
      - ${PORT}:5000
    volumes:
      - ./piglatin:/app

  tests:
    build: ./piglatin
    command: "python -m unittest discover tests"
    environment:
      PORT: ${PORT}
      DEBUG: ${DEBUG}
      DATABASE_ENGINE: ${DATABASE_ENGINE}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: ${DATABASE_PORT}
    volumes:
      - ./piglatin:/app

  database:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
