version: "3"
services:
  piglatin:
    build: ./piglatin
    depends_on:
      - database
      - cache
    environment:
      PORT: ${PORT}
      DEBUG: ${DEBUG}
      DATABASE_ENGINE: ${DATABASE_ENGINE}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: ${DATABASE_PORT}
      MAIL_SERVER: ${MAIL_SERVER}
      MAIL_PORT: ${MAIL_PORT}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    ports:
      - ${PORT}:5000
    volumes:
      - ./piglatin:/app

  docs:
    image: swaggerapi/swagger-ui
    ports:
      - 5001:8080
    environment:
      SWAGGER_JSON: /docs/api.yaml
    volumes:
      - ./piglatin/api-docs/:/docs

  database:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - db:/var/lib/postgresql/data

  smtp4dev:
    image: rnwood/smtp4dev:v3
    ports:
      - "2525:25"
      - "3001:80"

  cache:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data

  prometheus:
    image: prom/prometheus:v2.36.2
    ports:
      - "9090:9090"
    command:
      - "--web.enable-lifecycle"
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--log.level=warn"
    volumes:
      - ./docker/prometheus:/etc/prometheus
      - prometheus-data:/prometheus

volumes:
  db:
    driver: local
  cache:
    driver: local
  prometheus-data:
    driver: local
